language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
notifications:
  email:
    on_failure: never
    on_success: never
