language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy
notifications:
  email:
    on_failure: never
    on_success: never
