language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
after_success:
  - yarn run deploy
deploy:
  skip_cleanup: true
notifications:
  email:
    on_failure: never
    on_success: never
